import { desc, eq, gt } from "drizzle-orm";
import { db } from "@/db";
import { companies, passkeys, roles, sessions, users } from "@/db/schema";
import { createUserAction, changeEmailAction, changeRoleAction, deactivateUserAction, reactivateUserAction, resendActivationAction, updateNameAction } from "@/app/actions/users";
import { reauthenticateAction, revokeAllSessionsAction, revokePasskeyAction, revokeSessionAction } from "@/app/actions/security";
import { setSellerCompanyAction } from "@/app/actions/business";
import { ActionForm } from "@/components/action-form";
import { requireAdminPage } from "@/lib/authorization";

export default async function UsersPage() {
  await requireAdminPage("users.manage");
  const records = await db.select({ id: users.id, name: users.name, email: users.email, phone: users.phone, status: users.status, role: roles.code, version: users.version, companyId: users.companyId }).from(users).innerJoin(roles, eq(roles.id, users.roleId)).orderBy(users.name);
  const companyList = await db.select({ id: companies.id, name: companies.name }).from(companies).where(eq(companies.isActive, true)).orderBy(companies.name);
  const activeSessions = await db.select({ id: sessions.id, userId: sessions.userId, createdAt: sessions.createdAt, expiresAt: sessions.expiresAt, userAgent: sessions.userAgent }).from(sessions).where(gt(sessions.expiresAt, new Date())).orderBy(desc(sessions.createdAt));
  const userPasskeys = await db.select({ id: passkeys.id, userId: passkeys.userId, name: passkeys.name }).from(passkeys);
  return <div className="stack gap-lg"><h1>Usuarios</h1>
    <ActionForm action={reauthenticateAction} submitLabel="Confirmar identidad"><p>Confirma tu contraseña y segundo factor antes de acciones sensibles.</p><label>Contraseña<input name="password" type="password" required /></label><label>Código 2FA<input name="totp" inputMode="numeric" autoComplete="one-time-code" required /></label></ActionForm>
    <section className="card"><h2>Crear usuario</h2><ActionForm action={createUserAction} submitLabel="Crear y enviar invitación"><label>Nombre completo<input name="name" required /></label><label>Correo<input name="email" type="email" required /></label><label>Teléfono<input name="phone" required /></label><label>Empresa <span className="field-hint">obligatoria para vendedores</span><select name="companyId" defaultValue=""><option value="">— Sin empresa —</option>{companyList.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Rol<select name="role" defaultValue="SELLER"><option value="SELLER">Vendedor</option><option value="COMMERCIAL_MANAGER">Gerencia comercial</option><option value="ADMINISTRATIVE_MANAGER">Gerencia administrativa</option><option value="ADMIN">Administrador</option></select></label></ActionForm></section>
    <section><h2>Directorio</h2><div className="user-grid">{records.map((user) => <article className="card stack" key={user.id}><div><h3>{user.name}</h3><p>{user.email}<br />{user.phone}</p><span className="badge">{user.role}</span> <span className="badge">{user.status}</span></div>
      <form action={changeRoleAction} className="row"><input type="hidden" name="userId" value={user.id} />{!user.companyId && <label><span className="sr-only">Empresa (si pasa a vendedor)</span><select name="companyId" defaultValue=""><option value="">Empresa (si será vendedor)</option>{companyList.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<input type="hidden" name="version" value={user.version} /><label><span className="sr-only">Nuevo rol</span><select name="role" defaultValue={user.role}><option value="SELLER">Vendedor</option><option value="COMMERCIAL_MANAGER">Gerencia comercial</option><option value="ADMINISTRATIVE_MANAGER">Gerencia administrativa</option><option value="ADMIN">Administrador</option></select></label><button className="secondary">Cambiar rol</button></form>
      {user.role === "SELLER" && <ActionForm action={setSellerCompanyAction} submitLabel="Cambiar empresa" variant="secondary" className="row"><input type="hidden" name="userId" value={user.id} /><label><span className="sr-only">Empresa</span><select name="companyId" defaultValue={user.companyId ?? ""} required>{companyList.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label></ActionForm>}
      <form action={updateNameAction} className="row"><input type="hidden" name="userId" value={user.id} /><input type="hidden" name="version" value={user.version} /><label><span className="sr-only">Nombre completo</span><input name="name" defaultValue={user.name} required /></label><button className="secondary">Cambiar nombre</button></form>
      <form action={changeEmailAction} className="row"><input type="hidden" name="userId" value={user.id} /><input type="hidden" name="version" value={user.version} /><label><span className="sr-only">Nuevo correo</span><input name="email" type="email" placeholder="Nuevo correo verificado" required /></label><button className="secondary">Solicitar cambio</button></form>
      {user.status === "ACTIVE" ? <form action={deactivateUserAction}><input type="hidden" name="userId" value={user.id} /><input type="hidden" name="version" value={user.version} /><button className="danger">Desactivar</button></form> : user.status === "INACTIVE" ? <form action={reactivateUserAction}><input type="hidden" name="userId" value={user.id} /><input type="hidden" name="version" value={user.version} /><button>Reactivar por email</button></form> : <form action={resendActivationAction}><input type="hidden" name="userId" value={user.id} /><input type="hidden" name="version" value={user.version} /><button>Reenviar activación</button></form>}
      <details><summary>Sesiones y passkeys</summary><div className="stack">{activeSessions.filter((item) => item.userId === user.id).map((item) => <form action={revokeSessionAction} className="row" key={item.id}><input type="hidden" name="sessionId" value={item.id} /><span>{item.userAgent?.slice(0, 70) || "Dispositivo desconocido"}</span><button className="secondary">Revocar</button></form>)}<form action={revokeAllSessionsAction}><input type="hidden" name="userId" value={user.id} /><button className="danger secondary">Revocar todas</button></form>{userPasskeys.filter((item) => item.userId === user.id).map((item) => <form action={revokePasskeyAction} className="row" key={item.id}><input type="hidden" name="passkeyId" value={item.id} /><span>{item.name || "Passkey"}</span><button className="danger secondary">Revocar passkey</button></form>)}</div></details>
    </article>)}</div></section>
  </div>;
}
